spring:
  application:
    name: mirujima_BE
  lifecycle:
    timeout-per-shutdown-phase: 120

  datasource:
    url: jdbc:mysql://localhost:3306/mirujima
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  expiredAccessTokenMs: 3600000
  expiredRefreshTokenMs: 86400000
  secretKey: mirujima_jwt_key_#@!#_mirujima_jwt_key_#@!#

## Jasypt
jasypt:
  encryptor:
    key: torip_jasypt_key_#@!#

server:
  shutdown: graceful
  port: 8081

cloud:
  aws:
    credentials:
      access-key: ENC(QtldJ/h2U1UGb0Zfmf2RkggGD08nRsPcQxkSF2+xyhE=)
      secret-key: ENC(ZtjaK/1Tb791Ju8ay/v5NSMSH5fmupELDujmeestR+BGOSwRLhB0sVtfRMmRmknXwF/zrgmvP58=)
    region:
      static: ENC(x6/uuqcHpKqcLwYSWMfOZtRPHXBGSejO)
    s3:
      bucket: ENC(5RyziorhkYWj9Zxqxt3Ykg==)