spring:
  application:
    name: mirujima_BE
  lifecycle:
    timeout-per-shutdown-phase: 120

  datasource:
    url: ENC(1KQa0Ks9zo7H6t0wbRWaL/3Tm2YNrULWj+Eqeh7p5y8Ex7SW2+aDXKSoEt5QKm0B6JdQd3Gq00nitkkHRg6UbEl2nFytmEFOgcITwh+eKhuXeVYF/fsGAGhUS4sGbvhaG818pzxxU48=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(nt7qS4UJ8rJHy/vl+da+WT77wyJCBVV1)
    password: ENC(sHkQj7hh8U0z5fQPO11ZUVyCp2K0Vp3g)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#  data:
#    redis:
#      host: ENC(kipmZRoj9LTcSHFAc20ub6Yq5RXDU/zzrOGL8lMkos2AO5p9N2czfiN9LJ7Lq2Djuwb7dOeFieCXT1NKvAoDNQ==)
#      port: 6379

jwt:
  expiredAccessTokenMs: 3600000
  expiredRefreshTokenMs: 86400000
  secretKey: ENC(lh1kMo8tAKIdFO/qo3/D3uZY45ZGJ5W+OFTFjY8in/9LJR+Qs0QyV0S6FL1zFFznYPmoCLZcx2U=)

## Jasypt
jasypt:
  encryptor:
    key: ${jasypt_key}

server:
  shutdown: graceful
  port: 8081

cloud:
  aws:
    credentials:
      access-key: ENC(QtldJ/h2U1UGb0Zfmf2RkggGD08nRsPcQxkSF2+xyhE=)
      secret-key: ENC(ZtjaK/1Tb791Ju8ay/v5NSMSH5fmupELDujmeestR+BGOSwRLhB0sVtfRMmRmknXwF/zrgmvP58=)
    region:
      static: ENC(x6/uuqcHpKqcLwYSWMfOZtRPHXBGSejO)
    s3:
      bucket: ENC(5RyziorhkYWj9Zxqxt3Ykg==)

google:
  client:
    id: ENC(LqH5cp73vvA0SKrCBKYsw9FbKIpzNv7LizNNQsbmLo3dERMItQ0YvxAMuyZRNpKcM4UFYhp2MmGkKlkD7Mwq7pwGcjJKuaTjDsRDvf/3KZqVHpR7glWcpA==)
    secret: ENC(CF4gkdLbDhgjaGClGroG4lem8Ih+1COwgJ2FsgVvixOWSRpzDfyVeqCs4Lmfu8/x)
  redirect:
    uri: ENC(EDSq6OSdVfhoAf3RShzyHAK+zH3oS94v2yWgdyOdjc85OvnqroBReVocEcAsOMUM)
